name: CI
 
on:
  push:
    branches: ["main"]

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions: write-all # TODO: narrow
 
jobs:
  build:
      name: Build and Test
      timeout-minutes: 15
      runs-on: ubuntu-latest
 
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
 
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'yarn'
 
        - name: Install dependencies
          run: yarn
 
        - name: Build
          run: yarn build
 
        - name: Test
          run: yarn test

        - name: Create Release Pull Request or Publish to npm
          id: changesets
          uses: changesets/action@v1
          with:
            publish: yarn publish-packages 
            commit: 'chore: release notes'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
